language: android
jdk: oraclejdk7

android:
  components:
    - tools
    - platform-tools
    # The BuildTools version used by your project
    - build-tools-23.0.2
    # The SDK version used to compile your project
    - android-23
    # Additional components
    - extra-android-m2repository
    - extra-google-google_play_services
    - extra-google-m2repository
    # System image for running Android (integration) tests
    - sys-img-armeabi-v7a-android-21
script:
  - ./gradlew testDebugUnitTest
  - ./gradlew assembleDebug